// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/inbound/user_service_port.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	request "github.com/gieart87/gohexaclean/internal/dto/request"
	response "github.com/gieart87/gohexaclean/internal/dto/response"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockUserServicePort is a mock of UserServicePort interface.
type MockUserServicePort struct {
	ctrl     *gomock.Controller
	recorder *MockUserServicePortMockRecorder
}

// MockUserServicePortMockRecorder is the mock recorder for MockUserServicePort.
type MockUserServicePortMockRecorder struct {
	mock *MockUserServicePort
}

// NewMockUserServicePort creates a new mock instance.
func NewMockUserServicePort(ctrl *gomock.Controller) *MockUserServicePort {
	mock := &MockUserServicePort{ctrl: ctrl}
	mock.recorder = &MockUserServicePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServicePort) EXPECT() *MockUserServicePortMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserServicePort) CreateUser(ctx context.Context, req *request.CreateUserRequest) (*response.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, req)
	ret0, _ := ret[0].(*response.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserServicePortMockRecorder) CreateUser(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserServicePort)(nil).CreateUser), ctx, req)
}

// DeleteUser mocks base method.
func (m *MockUserServicePort) DeleteUser(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserServicePortMockRecorder) DeleteUser(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserServicePort)(nil).DeleteUser), ctx, id)
}

// GetUserByEmail mocks base method.
func (m *MockUserServicePort) GetUserByEmail(ctx context.Context, email string) (*response.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*response.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserServicePortMockRecorder) GetUserByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserServicePort)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockUserServicePort) GetUserByID(ctx context.Context, id uuid.UUID) (*response.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*response.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserServicePortMockRecorder) GetUserByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserServicePort)(nil).GetUserByID), ctx, id)
}

// ListUsers mocks base method.
func (m *MockUserServicePort) ListUsers(ctx context.Context, page, limit int) ([]*response.UserResponse, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, page, limit)
	ret0, _ := ret[0].([]*response.UserResponse)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockUserServicePortMockRecorder) ListUsers(ctx, page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockUserServicePort)(nil).ListUsers), ctx, page, limit)
}

// Login mocks base method.
func (m *MockUserServicePort) Login(ctx context.Context, req *request.LoginRequest) (*response.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, req)
	ret0, _ := ret[0].(*response.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserServicePortMockRecorder) Login(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserServicePort)(nil).Login), ctx, req)
}

// UpdateUser mocks base method.
func (m *MockUserServicePort) UpdateUser(ctx context.Context, id uuid.UUID, req *request.UpdateUserRequest) (*response.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, id, req)
	ret0, _ := ret[0].(*response.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserServicePortMockRecorder) UpdateUser(ctx, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserServicePort)(nil).UpdateUser), ctx, id, req)
}
